openapi: 3.0.0
info:
  title: Moon Phases
  version: '1'
  description: >-
    Moon Phases is a simple tool for getting the moon phases. It returns the
    moon phase for a given date.
  contact:
    name: APIVerve
    url: https://apiverve.com
    email: hello@apiverve.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.apiverve.com
    description: Production server
security:
  - ApiKeyAuth: []
paths:
  /v1/moonphases:
    get:
      summary: Moon Phases
      description: >-
        Moon Phases is a simple tool for getting the moon phases. It returns the
        moon phase for a given date.
      operationId: moonphases
      tags:
        - null
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  data:
                    type: object
        '400':
          description: Bad Request - Invalid parameters
        '401':
          description: Unauthorized - Invalid or missing API key
        '429':
          description: Too Many Requests - Rate limit exceeded
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
