openapi: 3.0.0
info:
  title: Shoe Size Converter
  version: '1'
  description: >-
    Shoe Size Converter is a tool for converting shoe sizes between US, UK, EU,
    CM, JP, AU, MX, and KR standards. It supports men, women, unisex, and child
    sizes.
  contact:
    name: APIVerve
    url: https://apiverve.com
    email: hello@apiverve.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.apiverve.com
    description: Production server
security:
  - ApiKeyAuth: []
paths:
  /v1/shoesizeconverter:
    get:
      summary: Shoe Size Converter
      description: >-
        Shoe Size Converter is a tool for converting shoe sizes between US, UK,
        EU, CM, JP, AU, MX, and KR standards. It supports men, women, unisex,
        and child sizes.
      operationId: shoesizeconverter
      tags:
        - null
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  data:
                    type: object
        '400':
          description: Bad Request - Invalid parameters
        '401':
          description: Unauthorized - Invalid or missing API key
        '429':
          description: Too Many Requests - Rate limit exceeded
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
