openapi: 3.0.0
info:
  title: HTML Entities Encoder/Decoder
  version: '1'
  description: >-
    HTML Entities Encoder/Decoder is a tool for encoding and decoding HTML
    entities. It converts special characters to HTML entities and vice versa to
    prevent XSS attacks and display special characters properly.
  contact:
    name: APIVerve
    url: https://apiverve.com
    email: hello@apiverve.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.apiverve.com
    description: Production server
security:
  - ApiKeyAuth: []
paths:
  /v1/htmlentities:
    get:
      summary: HTML Entities Encoder/Decoder
      description: >-
        HTML Entities Encoder/Decoder is a tool for encoding and decoding HTML
        entities. It converts special characters to HTML entities and vice versa
        to prevent XSS attacks and display special characters properly.
      operationId: htmlentities
      tags:
        - null
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  data:
                    type: object
        '400':
          description: Bad Request - Invalid parameters
        '401':
          description: Unauthorized - Invalid or missing API key
        '429':
          description: Too Many Requests - Rate limit exceeded
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
