openapi: 3.0.0
info:
  title: Chuck Norris Jokes
  version: '1'
  description: >-
    Chuck Norris Jokes is a simple tool for getting Chuck Norris jokes. It
    returns a random Chuck Norris joke.
  contact:
    name: APIVerve
    url: https://apiverve.com
    email: hello@apiverve.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.apiverve.com
    description: Production server
security:
  - ApiKeyAuth: []
paths:
  /v1/chucknorris:
    get:
      summary: Chuck Norris Jokes
      description: >-
        Chuck Norris Jokes is a simple tool for getting Chuck Norris jokes. It
        returns a random Chuck Norris joke.
      operationId: chucknorris
      tags:
        - null
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  data:
                    type: object
        '400':
          description: Bad Request - Invalid parameters
        '401':
          description: Unauthorized - Invalid or missing API key
        '429':
          description: Too Many Requests - Rate limit exceeded
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
