openapi: 3.0.0
info:
  title: Contact Extractor
  version: '1'
  description: >-
    Contact Extractor is a simple tool for extracting contact data from a
    website URL. It returns the contact emails, phone numbers, and places.
  contact:
    name: APIVerve
    url: https://apiverve.com
    email: hello@apiverve.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.apiverve.com
    description: Production server
security:
  - ApiKeyAuth: []
paths:
  /v1/contactextractor:
    get:
      summary: Contact Extractor
      description: >-
        Contact Extractor is a simple tool for extracting contact data from a
        website URL. It returns the contact emails, phone numbers, and places.
      operationId: contactextractor
      tags:
        - null
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  data:
                    type: object
        '400':
          description: Bad Request - Invalid parameters
        '401':
          description: Unauthorized - Invalid or missing API key
        '429':
          description: Too Many Requests - Rate limit exceeded
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
