openapi: 3.0.0
info:
  title: Text to Color
  version: '1'
  description: >-
    Text to Color is a simple tool for converting color from natural language.
    It returns the color code based on the text provided.
  contact:
    name: APIVerve
    url: https://apiverve.com
    email: hello@apiverve.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.apiverve.com
    description: Production server
security:
  - ApiKeyAuth: []
paths:
  /v1/texttocolor:
    get:
      summary: Text to Color
      description: >-
        Text to Color is a simple tool for converting color from natural
        language. It returns the color code based on the text provided.
      operationId: texttocolor
      tags:
        - null
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  data:
                    type: object
        '400':
          description: Bad Request - Invalid parameters
        '401':
          description: Unauthorized - Invalid or missing API key
        '429':
          description: Too Many Requests - Rate limit exceeded
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
