openapi: 3.0.0
info:
  title: Card Generator
  version: '1'
  description: >-
    Card Generator is a simple tool for generating test/sample card numbers. It
    returns a list of card numbers for testing.
  contact:
    name: APIVerve
    url: https://apiverve.com
    email: hello@apiverve.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.apiverve.com
    description: Production server
security:
  - ApiKeyAuth: []
paths:
  /v1/cardgenerator:
    get:
      summary: Card Generator
      description: >-
        Card Generator is a simple tool for generating test/sample card numbers.
        It returns a list of card numbers for testing.
      operationId: cardgenerator
      tags:
        - null
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  data:
                    type: object
        '400':
          description: Bad Request - Invalid parameters
        '401':
          description: Unauthorized - Invalid or missing API key
        '429':
          description: Too Many Requests - Rate limit exceeded
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
