openapi: 3.0.0
info:
  title: Meteorite Landings
  version: '1'
  description: >-
    Meteorites is a simple tool for getting meteorite data. It returns a list of
    meteorites that have fallen to Earth.
  contact:
    name: APIVerve
    url: https://apiverve.com
    email: hello@apiverve.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.apiverve.com
    description: Production server
security:
  - ApiKeyAuth: []
paths:
  /v1/meteorites:
    get:
      summary: Meteorite Landings
      description: >-
        Meteorites is a simple tool for getting meteorite data. It returns a
        list of meteorites that have fallen to Earth.
      operationId: meteorites
      tags:
        - null
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  data:
                    type: object
        '400':
          description: Bad Request - Invalid parameters
        '401':
          description: Unauthorized - Invalid or missing API key
        '429':
          description: Too Many Requests - Rate limit exceeded
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
