openapi: 3.0.0
info:
  title: Zip Codes Lookup
  version: '1'
  description: >-
    Zip Codes Lookup is a simple tool for looking up the zip codes of a city. It
    returns the zip codes of the city.
  contact:
    name: APIVerve
    url: https://apiverve.com
    email: hello@apiverve.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.apiverve.com
    description: Production server
security:
  - ApiKeyAuth: []
paths:
  /v1/zipcodes:
    get:
      summary: Zip Codes Lookup
      description: >-
        Zip Codes Lookup is a simple tool for looking up the zip codes of a
        city. It returns the zip codes of the city.
      operationId: zipcodes
      tags:
        - null
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  data:
                    type: object
        '400':
          description: Bad Request - Invalid parameters
        '401':
          description: Unauthorized - Invalid or missing API key
        '429':
          description: Too Many Requests - Rate limit exceeded
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
