openapi: 3.0.0
info:
  title: SPF Validator
  version: '1'
  description: >-
    SPF Validator checks the Sender Policy Framework (SPF) DNS record for a
    domain to verify if it’s valid and optionally whether a given IP address is
    authorized to send emails for that domain.
  contact:
    name: APIVerve
    url: https://apiverve.com
    email: hello@apiverve.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.apiverve.com
    description: Production server
security:
  - ApiKeyAuth: []
paths:
  /v1/spfvalidator:
    get:
      summary: SPF Validator
      description: >-
        SPF Validator checks the Sender Policy Framework (SPF) DNS record for a
        domain to verify if it’s valid and optionally whether a given IP address
        is authorized to send emails for that domain.
      operationId: spfvalidator
      tags:
        - null
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  data:
                    type: object
        '400':
          description: Bad Request - Invalid parameters
        '401':
          description: Unauthorized - Invalid or missing API key
        '429':
          description: Too Many Requests - Rate limit exceeded
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
