openapi: 3.0.0
info:
  title: Ring Size Converter
  version: '1'
  description: >-
    Ring Size Converter is a tool for converting ring sizes between US, UK, EU,
    JP, CH, and AU standards. It can also convert from diameter measurements in
    millimeters.
  contact:
    name: APIVerve
    url: https://apiverve.com
    email: hello@apiverve.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.apiverve.com
    description: Production server
security:
  - ApiKeyAuth: []
paths:
  /v1/ringsizeconverter:
    get:
      summary: Ring Size Converter
      description: >-
        Ring Size Converter is a tool for converting ring sizes between US, UK,
        EU, JP, CH, and AU standards. It can also convert from diameter
        measurements in millimeters.
      operationId: ringsizeconverter
      tags:
        - null
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  data:
                    type: object
        '400':
          description: Bad Request - Invalid parameters
        '401':
          description: Unauthorized - Invalid or missing API key
        '429':
          description: Too Many Requests - Rate limit exceeded
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
