openapi: 3.0.0
info:
  title: Open Source Licenses
  version: '1'
  description: >-
    Open Source Licenses is a simple tool for getting information on open source
    licenses. It returns information on various open source licenses.
  contact:
    name: APIVerve
    url: https://apiverve.com
    email: hello@apiverve.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.apiverve.com
    description: Production server
security:
  - ApiKeyAuth: []
paths:
  /v1/openlicenses:
    get:
      summary: Open Source Licenses
      description: >-
        Open Source Licenses is a simple tool for getting information on open
        source licenses. It returns information on various open source licenses.
      operationId: openlicenses
      tags:
        - null
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  data:
                    type: object
        '400':
          description: Bad Request - Invalid parameters
        '401':
          description: Unauthorized - Invalid or missing API key
        '429':
          description: Too Many Requests - Rate limit exceeded
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
