openapi: 3.0.0
info:
  title: Loan Calculator
  version: '1'
  description: >-
    Loan Payment Calculator is a simple tool for calculating loan payments. It
    returns the monthly payment, total interest, and more.
  contact:
    name: APIVerve
    url: https://apiverve.com
    email: hello@apiverve.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.apiverve.com
    description: Production server
security:
  - ApiKeyAuth: []
paths:
  /v1/loanpaymentcalculator:
    get:
      summary: Loan Calculator
      description: >-
        Loan Payment Calculator is a simple tool for calculating loan payments.
        It returns the monthly payment, total interest, and more.
      operationId: loanpaymentcalculator
      tags:
        - null
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  data:
                    type: object
        '400':
          description: Bad Request - Invalid parameters
        '401':
          description: Unauthorized - Invalid or missing API key
        '429':
          description: Too Many Requests - Rate limit exceeded
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
