openapi: 3.0.0
info:
  title: Parts Of Speech
  version: '1'
  description: >-
    Parts Of Speech is a simple tool for extracting nouns, verbs, adjectives,
    adverbs, etc. from text. It returns the extracted words based on the part of
    speech specified.
  contact:
    name: APIVerve
    url: https://apiverve.com
    email: hello@apiverve.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.apiverve.com
    description: Production server
security:
  - ApiKeyAuth: []
paths:
  /v1/partsofspeech:
    get:
      summary: Parts Of Speech
      description: >-
        Parts Of Speech is a simple tool for extracting nouns, verbs,
        adjectives, adverbs, etc. from text. It returns the extracted words
        based on the part of speech specified.
      operationId: partsofspeech
      tags:
        - null
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  data:
                    type: object
        '400':
          description: Bad Request - Invalid parameters
        '401':
          description: Unauthorized - Invalid or missing API key
        '429':
          description: Too Many Requests - Rate limit exceeded
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
