openapi: 3.0.0
info:
  title: Currency Converter
  version: '1'
  description: >-
    Currency Converter is a simple tool for converting currency rates. It
    returns the converted currency rate based on the amount and currency
    provided.
  contact:
    name: APIVerve
    url: https://apiverve.com
    email: hello@apiverve.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.apiverve.com
    description: Production server
security:
  - ApiKeyAuth: []
paths:
  /v1/currencyconverter:
    get:
      summary: Currency Converter
      description: >-
        Currency Converter is a simple tool for converting currency rates. It
        returns the converted currency rate based on the amount and currency
        provided.
      operationId: currencyconverter
      tags:
        - null
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  data:
                    type: object
        '400':
          description: Bad Request - Invalid parameters
        '401':
          description: Unauthorized - Invalid or missing API key
        '429':
          description: Too Many Requests - Rate limit exceeded
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
