openapi: 3.0.0
info:
  title: BIN Lookup
  version: '1'
  description: >-
    BIN Lookup is a simple tool for looking up BIN number information. It
    returns information such as the bank, card type, and more based on the BIN
    number provided.
  contact:
    name: APIVerve
    url: https://apiverve.com
    email: hello@apiverve.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.apiverve.com
    description: Production server
security:
  - ApiKeyAuth: []
paths:
  /v1/binlookup:
    get:
      summary: BIN Lookup
      description: >-
        BIN Lookup is a simple tool for looking up BIN number information. It
        returns information such as the bank, card type, and more based on the
        BIN number provided.
      operationId: binlookup
      tags:
        - null
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  data:
                    type: object
        '400':
          description: Bad Request - Invalid parameters
        '401':
          description: Unauthorized - Invalid or missing API key
        '429':
          description: Too Many Requests - Rate limit exceeded
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
