openapi: 3.0.0
info:
  title: Tense Converter
  version: '1'
  description: >-
    Tense Converter is a simple tool for converting text to past or future
    tense. It returns the text converted to the specified tense.
  contact:
    name: APIVerve
    url: https://apiverve.com
    email: hello@apiverve.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.apiverve.com
    description: Production server
security:
  - ApiKeyAuth: []
paths:
  /v1/tenseconverter:
    get:
      summary: Tense Converter
      description: >-
        Tense Converter is a simple tool for converting text to past or future
        tense. It returns the text converted to the specified tense.
      operationId: tenseconverter
      tags:
        - null
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  data:
                    type: object
        '400':
          description: Bad Request - Invalid parameters
        '401':
          description: Unauthorized - Invalid or missing API key
        '429':
          description: Too Many Requests - Rate limit exceeded
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
