openapi: 3.0.0
info:
  title: Marine Weather
  version: '1'
  description: >-
    Marine Weather is a simple tool for getting marine weather data. It returns
    the current weather conditions in coordinates within the ocean and sea.
  contact:
    name: APIVerve
    url: https://apiverve.com
    email: hello@apiverve.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.apiverve.com
    description: Production server
security:
  - ApiKeyAuth: []
paths:
  /v1/marineweather:
    get:
      summary: Marine Weather
      description: >-
        Marine Weather is a simple tool for getting marine weather data. It
        returns the current weather conditions in coordinates within the ocean
        and sea.
      operationId: marineweather
      tags:
        - null
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  data:
                    type: object
        '400':
          description: Bad Request - Invalid parameters
        '401':
          description: Unauthorized - Invalid or missing API key
        '429':
          description: Too Many Requests - Rate limit exceeded
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
