openapi: 3.0.0
info:
  title: Routing Number Lookup
  version: '1'
  description: >-
    Routing Number Lookup is a simple tool for looking up routing number
    information for USA Banks. It returns information such as the bank,
    location, and more based on the routing number provided.
  contact:
    name: APIVerve
    url: https://apiverve.com
    email: hello@apiverve.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.apiverve.com
    description: Production server
security:
  - ApiKeyAuth: []
paths:
  /v1/routinglookup:
    get:
      summary: Routing Number Lookup
      description: >-
        Routing Number Lookup is a simple tool for looking up routing number
        information for USA Banks. It returns information such as the bank,
        location, and more based on the routing number provided.
      operationId: routinglookup
      tags:
        - null
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  data:
                    type: object
        '400':
          description: Bad Request - Invalid parameters
        '401':
          description: Unauthorized - Invalid or missing API key
        '429':
          description: Too Many Requests - Rate limit exceeded
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
