openapi: 3.0.0
info:
  title: Street Address Parser
  version: '1'
  description: >-
    Street Address Parser is a simple tool for parsing a US street addresses. It
    returns the parsed components of the street address provided.
  contact:
    name: APIVerve
    url: https://apiverve.com
    email: hello@apiverve.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.apiverve.com
    description: Production server
security:
  - ApiKeyAuth: []
paths:
  /v1/streetaddressparser:
    get:
      summary: Street Address Parser
      description: >-
        Street Address Parser is a simple tool for parsing a US street
        addresses. It returns the parsed components of the street address
        provided.
      operationId: streetaddressparser
      tags:
        - null
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  data:
                    type: object
        '400':
          description: Bad Request - Invalid parameters
        '401':
          description: Unauthorized - Invalid or missing API key
        '429':
          description: Too Many Requests - Rate limit exceeded
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
