openapi: 3.0.0
info:
  title: Phone Number Validator
  version: '1'
  description: >-
    Phone Number Validator is a simple tool for validating if a phone number is
    valid or not. It checks the phone number format and the country code to see
    if the phone number is valid.
  contact:
    name: APIVerve
    url: https://apiverve.com
    email: hello@apiverve.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.apiverve.com
    description: Production server
security:
  - ApiKeyAuth: []
paths:
  /v1/phonenumbervalidator:
    get:
      summary: Phone Number Validator
      description: >-
        Phone Number Validator is a simple tool for validating if a phone number
        is valid or not. It checks the phone number format and the country code
        to see if the phone number is valid.
      operationId: phonenumbervalidator
      tags:
        - null
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  data:
                    type: object
        '400':
          description: Bad Request - Invalid parameters
        '401':
          description: Unauthorized - Invalid or missing API key
        '429':
          description: Too Many Requests - Rate limit exceeded
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
