openapi: 3.0.0
info:
  title: SEO Quick Validator
  version: '1'
  description: >-
    SEO Validator is a simple tool for validating SEO metrics. It returns a list
    of issues that need to be fixed to improve the SEO metrics of a web page.
  contact:
    name: APIVerve
    url: https://apiverve.com
    email: hello@apiverve.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.apiverve.com
    description: Production server
security:
  - ApiKeyAuth: []
paths:
  /v1/seovalidator:
    get:
      summary: SEO Quick Validator
      description: >-
        SEO Validator is a simple tool for validating SEO metrics. It returns a
        list of issues that need to be fixed to improve the SEO metrics of a web
        page.
      operationId: seovalidator
      tags:
        - null
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  data:
                    type: object
        '400':
          description: Bad Request - Invalid parameters
        '401':
          description: Unauthorized - Invalid or missing API key
        '429':
          description: Too Many Requests - Rate limit exceeded
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
